shared:
  image: docker.ouroath.com:4443/docker.io/node:18
  environment:
    SD_TEMPLATE_PATH: ./template1.yaml
jobs:
  validate_template:
    requires: [~pr, ~commit]
    steps:
      - install_prerequisites: npm install -g screwdriver-template-main
      - validate_template: pipeline-template-validate
